INSERT INTO WAKA_ADMIN_USER (ADMIN_USER_ID, ACCOUNT, NAME, PASSWORD, ACTIVE_STATUS_FLAG) VALUES (-1,'admin','管理员','$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', true);

INSERT INTO WAKA_ADMIN_USER_ROLE_XREF (ADMIN_ROLE_ID, ADMIN_USER_ID) VALUES (-1,-1);
