INSERT INTO WAKA_ADMIN_ROLE (ADMIN_ROLE_ID, FRIENDLY_NAME, NAME) VALUES (-1,'超级管理员','ROLE_ADMIN');

INSERT INTO WAKA_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) VALUES (-1,-121);
INSERT INTO WAKA_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) VALUES (-1,-141);
INSERT INTO WAKA_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) VALUES (-1,-151);